name: GoatBot Runner

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Start GoatBot
        run: npm start
